ModProg/derive-where

ensure-no-std/src/lib.rs
non-msrv-tests/tests/util.rs
non-msrv-tests/tests/zeroize.rs
src/attr/default.rs
src/attr/field.rs
src/attr/item.rs
src/attr/skip.rs
src/attr/variant.rs
src/attr/zeroize_fqs.rs
src/data.rs
src/data/fields.rs
src/error.rs
src/input.rs
src/item.rs
src/test/basic.rs
src/test/bound.rs
src/test/enum_.rs
src/test/zeroize.rs
tests/tests.rs
tests/util.rs

A couple more remaining error case, a big one I just implemented is to check if the generics to bind are the same as the ones specified on the item itself.
```rust
#[derive_where(Clone; T)]
struct Test<T>(T);
```
Doesn't work anymore, this can be done with the standard `derive`.

More error cases

---

.github/workflows/format.yml

Taplo now supports running formatting checks and returning a status error on failure.

Run Taplo in CI

---

.config/topic.dic
.github/workflows/lint.yml
.github/workflows/test.yml
.github/workflows/validate.yml
CHANGELOG.md
Cargo.toml
README.md
ensure-no-std/Cargo.toml
ensure-no-std/src/lib.rs
non-msrv-tests/Cargo.toml
non-msrv-tests/tests/ui/zeroize/deprecated_drop.rs
non-msrv-tests/tests/ui/zeroize/deprecated_drop.stderr
non-msrv-tests/tests/ui/zeroize/item.stderr
non-msrv-tests/tests/ui/zeroize/zeroize.rs
non-msrv-tests/tests/ui/zeroize/zeroize.stderr
non-msrv-tests/tests/util.rs
non-msrv-tests/tests/zeroize.rs
src/attr/item.rs
src/error.rs
src/input.rs
src/lib.rs
src/test/zeroize.rs
src/trait_.rs
src/trait_/zeroize.rs
src/trait_/zeroize_on_drop.rs
src/util.rs

This is waiting for RustCrypto/utils#700 and a new release. Deprecates `Zeroize(drop)` in favor of `ZeroizeOnDrop`.

Implement `ZeroizeOnDrop`

---

src/data.rs
src/data/fields.rs
src/test/basic.rs
src/test/enum_.rs
src/test/skip.rs
src/trait_/common_ord.rs

See code generation tests, should be very self-explanatory.

Improve code generation of `Ord` and `PartialOrd`

---

CHANGELOG.md
Cargo.toml
README.md
crate_/Cargo.toml
crate_/src/lib.rs
ensure-no-std/Cargo.toml
non-msrv-tests/Cargo.toml
non-msrv-tests/tests/ui/item.rs
non-msrv-tests/tests/ui/item.stderr
non-msrv-tests/tests/ui/not-zeroize/item.stderr
non-msrv-tests/tests/ui/zeroize/item.stderr
non-msrv-tests/tests/ui/zeroize/zeroize.rs
non-msrv-tests/tests/ui/zeroize/zeroize.stderr
src/attr/item.rs
src/error.rs
src/input.rs
src/lib.rs
src/test/mod.rs
src/trait_.rs
src/trait_/zeroize.rs
src/trait_/zeroize_on_drop.rs

This addresses a suggestion I made in #36. It implements a placeholder attribute that is applies when a `derive_where` attribute is processed. Any subsequent calls to `derive_where` with different paths will error out when they find this attribute.
Additionally:
- Adds a `#[derive_where(crate = "derive_where_")]` option.
- Fixes some typos.
- Adds a check for `#[derive_where(Zeroize(crate = "::zeroize"))]` because this is already the default.
- Update zeroize.

Implement placeholder attribute to prevent multiple `derive_where`s with different paths

---

CHANGELOG.md
README.md
non-msrv-tests/tests/ui/non_item.rs
non-msrv-tests/tests/ui/non_item.stderr
src/lib.rs

Fixes #35.
I added a note in the README, but noticed that actually setting the path can produce some pretty unexpected behavior.
What do you think of adding an error if a `derive_where::derive_where` is found as not the first attribute? This isn't bulletproof of course because `derive_where_export::derive_where` could still remain undetected.

Attribute proc-macro follow up

---

src/attr/item.rs
src/error.rs
src/input.rs
src/lib.rs
src/test/basic.rs
src/test/bound.rs
src/test/clone.rs
src/test/enum_.rs
src/test/skip.rs
src/test/zeroize.rs
src/trait_.rs
src/trait_/clone.rs
src/trait_/debug.rs
src/trait_/default.rs
src/trait_/hash.rs
src/trait_/ord.rs
src/trait_/partial_eq.rs
src/trait_/partial_ord.rs
src/trait_/zeroize.rs
src/trait_/zeroize_on_drop.rs
tests/ui/item.rs
tests/ui/item.stderr

This mimics what Rust `std` does, when we know that `Copy` is implemented, no further code is required for `Clone`.
To make sure that we consider `Copy` implementation in separate `derive_where`s I made sure to merge `derive_where`s that have the same bounds beforehand.

Improve `Clone` code generation

---

README.md
src/lib.rs

Just discovered `derive_bounded`.
Fixed some spacing issue on the way, also removed the parentheses around the Crates.io label in the alternatives.
Cc https://github.com/lu-zero/derive_bounded/issues/2.

Add `derive_bounded` as an alternative

---

README.md
src/lib.rs

I discovered in https://github.com/lu-zero/derive_bounded/issues/2 that the examples on the front page might lead users to believe you have to write a `#[derive_where(..)]` for each trait, I improved the examples to not only use one trait.
Also fixed some wording about `Default` on `enum`s, Rusts supports this now.
EDIT: Looking at the README again, I noticed a lot of links were broken and missing, so I fixed that too.

Improve Examples

---

CHANGELOG.md
tests/ui/union.stderr

Apparently either `syn` or Rust nightly is going through some changes.

Fix UI tests

---

CHANGELOG.md
README.md
src/item.rs
src/lib.rs
src/test/discriminant.rs
src/trait_/common_ord.rs

See [Zulip](https://rust-lang.zulipchat.com/#narrow/stream/182449-t-compiler.2Fhelp/topic/enum.20discriminant.20size/near/388771801).
Yanking time ... cry me a river ...

Enforce default discriminant type for all representations and across editions

---

CHANGELOG.md
Cargo.toml

Actually after second though there isn't really a reason to yank v1.2.4, considering that it isn't actually broken *yet* and we don't even know if it ever will.

Prepare v1.2.5 release

---

.github/workflows/test.yml

Zeroize v1.7.0 raised the MSRV to v1.70, so when testing we should just pin it at v1.6.0.

Fix `zeroize` MSRV

---

CHANGELOG.md
src/test/bound.rs
src/trait_/clone.rs
tests/bound.rs

Still going to add some integration tests.
Fixes #86.

Fix wrong usage of `Copy` in `Clone` when bounds are present

---

CHANGELOG.md
src/lib.rs
src/test/basic.rs
src/test/bound.rs
src/test/clone.rs
src/test/discriminant.rs
src/test/enum_.rs
src/test/incomparable.rs
src/test/misc.rs
src/test/partial_ord.rs
src/test/skip.rs
src/test/zeroize.rs
tests/misc.rs
tests/skip/debug.rs

Fixes #91.
My understanding is that we should have done this all along anyway.
See the [Rust reference](https://doc.rust-lang.org/1.74.0/reference/attributes/derive.html?highlight=%23%5Bautomatically_derived%5D#the-automatically_derived-attribute).

Apply `#[automatically_derived]` to all generated implementations

---

.github/workflows/audit.yml
.github/workflows/format.yml
.github/workflows/lint.yml
.github/workflows/publish.yml
.github/workflows/spellcheck.yml
.github/workflows/test.yml
.github/workflows/validate.yml
src/attr/item.rs

- Don't run CI on every push, but only on the `main` branch and in PRs.
- Cancel CI when a new one is already run on a newer commit.
- Use [`CARGO_TERM_COLOR`](https://doc.rust-lang.org/1.74.0/cargo/reference/environment-variables.html#configuration-environment-variables).
- Use [`taiki-e/install-action`](https://github.com/taiki-e/install-action).
- Make sure to always checkout the repo first, which avoids some issues, like running actions.
- Add [Typos](https://crates.io/crates/typos) for spell checking.

Improve CI

---

CHANGELOG.md
src/lib.rs
src/test/bound.rs
src/test/clone.rs
src/test/mod.rs
src/test/partial_ord.rs
src/trait_.rs
src/trait_/clone.rs
src/trait_/common_ord.rs
src/trait_/debug.rs
src/trait_/default.rs
src/trait_/eq.rs
src/trait_/hash.rs
src/trait_/ord.rs
src/trait_/partial_eq.rs
src/trait_/partial_ord.rs
src/trait_/zeroize.rs
src/trait_/zeroize_on_drop.rs

Some more `Clone` and `PartialOrd` optimization.
Thank you @eric-seppanen for pointing it out.

Use optimized output for `Clone` and `PartialOrd` with custom bounds

---

Cargo.toml
src/data.rs
src/error.rs
src/input.rs
src/item.rs
src/lib.rs
src/trait_/clone.rs
src/trait_/common_ord.rs
src/trait_/debug.rs
src/trait_/default.rs
src/trait_/hash.rs
src/trait_/ord.rs
src/trait_/partial_eq.rs
src/trait_/partial_ord.rs
src/trait_/zeroize.rs
src/trait_/zeroize_on_drop.rs
tests/bound.rs
tests/cfg.rs
tests/hygiene.rs
tests/incomparable.rs
tests/misc.rs
tests/raw.rs
tests/safety.rs
tests/skip/field_trait.rs
tests/skip/struct_trait.rs
tests/skip/variant_trait.rs
tests/zeroize.rs

- **Fix clippy**
- **Fix typos**

Clippy + Typos

---

LICENSE-APACHE

My employer's automated license compliance bot got very confused because of these typos.

license: fix typos (!) in apache license text

---

CHANGELOG.md
src/test/zeroize.rs
src/trait_/zeroize_on_drop.rs

I noticed that the following would fail to compile:
```rust
#[derive_where(ZeroizeOnDrop)]
enum Test<T> {
A(PhantomData<T>),
#[derive_where(skip_inner)]
B(PhantomData<T>),
}
```
Because it produces the following:
```rust
impl<T> Drop for Test<T> {
fn drop(&mut self) {
match self {
Test::A(ref mut __field_0) => {
__field_0.zeroize_or_on_drop();
}
}
}
}
```
Instead, we now make sure to also cover variants that are skipped, but their body is just empty now.
See the test I added for a more complete example.

Support skipping only some variants with `ZeroizeOnDrop`

---

CHANGELOG.md
src/attr/item.rs
src/test/bound.rs

It's currently not possible to use higher rank trait bounds without providing custom predicate type bounds. Our particular use case is enabling "trivial bounds" without requiring the nightly feature. For context: https://github.com/rust-lang/rust/issues/48214#issuecomment-2799836786
For example:
```rust
// fails due to "the trait bound `std::string::String: std::marker::Copy` is not satisfied"
#[derive_where(Clone, Copy; String)]
struct TestThing {
a: String,
}
// Compiles! Copy is just not implemented due to String obviously not being copy, so it would compile error on use.
#[derive_where(Clone, Copy; for<'a> String)]
struct TestThing {
a: String,
}
```
This is useful for adding perfect derives to macro-generated structs. 
I'm not fully sure whether having a HRTB should make …

Feat: Allow lifetime for bounds in non-binded generic params

---

CHANGELOG.md
README.md
src/attr/item.rs
src/attr/skip.rs
src/data.rs
src/error.rs
src/lib.rs
src/test/bound.rs
src/test/clone.rs
src/trait_/clone.rs
tests/skip/field_trait.rs
tests/skip/struct_trait.rs
tests/skip/variant_trait.rs
tests/ui/not-zeroize/item_skip.rs
tests/ui/not-zeroize/item_skip.stderr
tests/ui/not-zeroize/skip.rs
tests/ui/not-zeroize/skip.stderr
tests/ui/skip.rs
tests/ui/skip.stderr
tests/ui/zeroize/item_skip.rs
tests/ui/zeroize/item_skip.stderr
tests/ui/zeroize/skip.rs
tests/ui/zeroize/skip.stderr
tests/util/mod.rs

skip(Clone)

---

CHANGELOG.md
README.md
src/attr.rs
src/attr/field.rs
src/attr/incomparable.rs
src/attr/item.rs
src/attr/skip.rs
src/attr/zeroize_fqs.rs
src/input.rs
src/lib.rs
src/test/zeroize.rs
src/trait_.rs
src/trait_/clone.rs
src/trait_/common_ord.rs
src/trait_/copy.rs
src/trait_/debug.rs
src/trait_/default.rs
src/trait_/eq.rs
src/trait_/hash.rs
src/trait_/ord.rs
src/trait_/partial_eq.rs
src/trait_/partial_ord.rs
src/trait_/zeroize.rs
src/trait_/zeroize_on_drop.rs
tests/ui.rs
tests/ui/not-zeroize-on-drop/zeroize-on-drop.rs
tests/ui/not-zeroize-on-drop/zeroize-on-drop.stderr
tests/ui/zeroize-on-drop/zeroize-on-drop.rs
tests/ui/zeroize-on-drop/zeroize-on-drop.stderr
tests/zeroize.rs

This PR adds a new option to `ZeroizeOnDrop`: `no_drop`. This will implement `ZeroizeOnDrop` without implementing `Drop`. Instead, it will assert that all fields implement `ZeroizeOnDrop` (not `Zeroize`!).
The second part of this PR reworks `DeriveTrait` and moves the ownership of derive related data to the actual `TraitImpl` instead of it just being a dummy-struct to implement `TraitImpl` over. Now we have to pass in less parameters to each method and can actually use `self` to store data.

Implement `ZeroizeOnDrop` without `Drop`

---

.config/topic.dic
CHANGELOG.md
src/test/basic.rs
src/test/bound.rs
src/test/zeroize.rs
src/trait_.rs
src/trait_/eq.rs
src/trait_/zeroize_on_drop.rs

This changes the implementation of `Eq` to not use `Eq::assert_receiver_is_total_eq()` and the implementation of `ZeroizeOnDrop` to not use `zeroite::__internal`. Both are `doc(hidden)` and therefor unstable APIs.
Resolves #115.

Stop Using Internal APIs

---

src/lib.rs

Just left a short documentation on why we are doing this here.

Document why we re-direct to a derive macro

---

CHANGELOG.md
README.md
src/test/discriminant.rs
src/trait_/common_ord.rs

Just leaving this here in case it turns out we don't need this validation ...

Remove C validation
